springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

server:
  port: 8084
  servlet:
    context-path: /api/bank


openapi:
  service:
    # API Gateway 포트
    url: http://localhost:8081