

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

server:
  port: 8084
  servlet:
    context-path: /api/bank


openapi:
  service:
    url: http://j10a505.p.ssafy.io/api/bank

spring:
  config:
    import: classpath:application-bank-priavte.yml
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

#logging
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: trace
