server:
  port: 8081


spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user:8082
          predicates:
            - Path=/api/user/**
        - id: community-service
          uri: http://community:8083
          predicates:
            - Path=/api/community/**








springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /api-docs
        name: API Gateway Service
      - url: http://community:8083/api-docs
        name: Community Service
      - url: http://user:8082/api-docs
        name: User Service


