
spring:
  application:
    name: gateway
  cloud:
    gateway:




      routes:

      # 스웨거
        - id: user-swagger
          uri: http://localhost:8081
          predicates:
            - Path=/api/user/swagger-ui/**

        - id: community-swagger
          uri: http://localhost:8081
          predicates:
            - Path=/api/community/swagger-ui/**

        - id: bank-swagger
          uri: http://localhost:8081
          predicates:
            - Path=/api/bank/swagger-ui/**

      # 로그인이 필요없는 서비스
        - id: auth-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/user/auth/**



      # 로그인이 필요한 서비스
        - id: group-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/user/groups/**
          filters:
            - AuthorizationHeaderFilter
#            - GroupFilter


        - id: user-service
#          uri: http://10.43.229.25:8082
          uri: http://localhost:8082
          predicates:
            - Path=/api/user/**
          filters:
            - AuthorizationHeaderFilter


        - id: community-service
#          uri: http://10.43.116.89:8083
          uri: http://localhost:8083
          predicates:
            - Path=/api/community/**
          filters:
            - AuthorizationHeaderFilter
#            - GroupFilter


        - id: bank-service
#          uri: http://10.43.68.76:8084
          uri: http://localhost:8084
          predicates:
            - Path=/api/bank/**
          filters:
            - AuthorizationHeaderFilter




jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVuyzboc03codHaHoGe24r43o39gur82ad47Dnkjernf4vkly9fF2o
  access:
    # 30분
    expiration_time: 1800000
  refresh:
    # 2주
    expiration_time: 1209600000