server:
  port: 8081





springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /api-docs
        name: API Gateway Service
      - url: /community/api-docs
        name: community
      - url: /user/api-docs
        name: user
      - url: /bank/api-docs
        name: bank



openapi:
  service:
    # API Gateway 포트
    url: http://localhost:8081

spring:
  config:
    import: classpath:application-private.yml
#    import: classpath:application-user-private-aws.yml
