
server:
  port: 8081


spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/user/**
        - id: community-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/community/**
        - id: bank-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/bank/**








springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /api-docs
        name: API Gateway Service
      - url: /community/api-docs
        name: community
      - url: /user/api-docs
        name: user
      - url: /bank/api-docs
        name: bank



openapi:
  service:
    # API Gateway 포트
    url: http://localhost:8081