server:
  port: 8081


spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user.default.svc.cluster.local:8082
          predicates:
            - Path=/api/user/**
        - id: community-service
          uri: http://community.default.svc.cluster.local:8083
          predicates:
            - Path=/api/community/**
        - id: bank-service
          uri: http://bank.default.svc.cluster.local:8084
          predicates:
            - Path=/api/bank/**
      globalcors:
        corsConfigurations:
          '[/**]': # 모든 경로에 대해 CORS 설정을 적용합니다.
            allowedOrigins: "http://j10a505.p.ssafy.io" # 허용할 도메인을 지정합니다. 여러 개의 도메인을 허용하려면 리스트 형태로 추가합니다.
            allowedMethods: # 허용할 HTTP 메서드를 지정합니다.
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: # 허용할 HTTP 헤더를 지정합니다.
              - Content-Type
              - Authorization
              - Accept
              - Origin
              - X-Requested-With
            allowCredentials: true # 크레덴셜(쿠키, HTTP 인증 및 클라이언트 SSL 인증 정보)을 지원하도록 허용합니다.







springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /api-docs
        name: API Gateway Service
      - url: /community/api-docs
        name: community
      - url: /user/api-docs
        name: user
      - url: /bank/api-docs
        name: bank



openapi:
  service:
    # API Gateway 포트
    url: http://j10a505.p.ssafy.io/api
