springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

server:
  port: 8083
  servlet:
    context-path: /api/community


openapi:
  service:
    # API Gateway 포트
    url: http://j10a505.p.ssafy.io/api
spring:
  profiles:
    active: local
  config:
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          format_sql: true

  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: file:/uploads/feed/

#logging
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: trace
