apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank
  template:
    metadata:
      labels:
        app: bank
    spec:
      containers:
        - name: bank
          image: minwoo540/momo:bank-latest
          ports:
            - containerPort: 8084
