springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

server:
  port: 8082
  servlet:
    contextPath: "/api/user"

spring:
  kafka:
    producer:
#      bootstrap-servers: "localhost:9092"
      bootstrap-servers: "my-kafka.default.svc.cluster.local:9092"
    consumer:
#      bootstrap-servers: "localhost:9092"
      bootstrap-servers: "my-kafka.default.svc.cluster.local:9092"
      group-id: "myGroup"

  config:
    import: classpath:application-private.yml
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true


#logging
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: trace


