


springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

server:
  port: 8082
  servlet:
    contextPath: "/api/user"

spring:
  config:
    import: classpath:application-private.yml
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true


#logging
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: trace




openapi:
  service:
    # API Gateway 포트
    url: http://localhost:8081