


springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

server:
  port: 8082
  servlet:
    contextPath: "/api/user"

openapi:
  service:
    # API Gateway 포트
    url: http://localhost:8081