# Datasource
spring:
  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      username: root
      password: 1234
    url: jdbc:mariadb://localhost:3306/momo?
  data:
    redis:
      host: j10a505.p.ssafy.io
      port: 6379
      password: holywater1357
      lettuce:
        pool:
          max-active: 8  # 연결풀에 할당할 최대 연결 수 (기본값: 8)
          max-idle: 8  # 연결풀에 유지할 최대 유휴 연결 수 (기본값: 8)
          min-idle: 0  # 연결풀에 유지할 최소 유휴 연결 수 (기본값: 0)

sms:
  api-key: NCSQMMB27ATDECT1
  api-secret-key: N5PCMCIYLSIIBCHODIMRFR3TPG3U558V
  url: https://api.coolsms.co.kr
  from-number: 01045786827


verification:
  secret-key: dbxcfwde
  algorithm : HmacSHA256

